In [1]:
import statfin

In [2]:
db = statfin.Vero()
db

statfin.PxWebAPI
  url: https://vero2.stat.fi/PXWeb/api/v1/fi
  index:
     Vero Vero

In [3]:
db.Vero

statfin.PxWebAPI
  url: https://vero2.stat.fi/PXWeb/api/v1/fi/Vero
  title: Vero
  index:
    (l) Elinkeinoverotilasto         1. Elinkeinovero
    (l) Henkiloasiakkaiden_tuloverot 2. Henkilöasiakkaiden tulovero
    (l) Kiinteistoverot              3. Kiinteistövero
    (l) Verotulojen_kehitys          4. Verotulojen kehitys
    (l) Valmistevero                 5. Valmistevero
    (l) Autovero                     6. Autovero
    (l) Tulorekisteri                7. Ennakonpidätyksen alaisten ansiotulojen kuukausitilasto

In [4]:
db.Vero.Henk

statfin.PxWebAPI
  url: https://vero2.stat.fi/PXWeb/api/v1/fi/Vero/Henkiloasiakkaiden_tuloverot
  title: 2. Henkilöasiakkaiden tulovero
  index:
    (l) lopulliset 1. Verotuksen päättymisajankohdan tiedot
    (l) ennakot    2. Ennakkotiedot

In [5]:
db.Vero.Henk.lopulliset

statfin.PxWebAPI
  url: https://vero2.stat.fi/PXWeb/api/v1/fi/Vero/Henkiloasiakkaiden_tuloverot/lopulliset
  title: 1. Verotuksen päättymisajankohdan tiedot
  index:
    (l) tulot          01. Tulot
    (l) vahennykset    02. Vähennykset
    (l) verot_maksut   03. Verot ja maksut
    (l) ennakot        04.  Ennakot, palautukset ja jäännösverot
    (l) verovelv       05. Tulot, vähennykset ja verot verovelvollisuuksittain
    (l) alue           06. Yleisesti verovelvollisten tulot, vähennykset ja verot alueittain
    (l) kuntaryh       07. Yleisesti verovelvollisten tulot, vähennykset ja verot kuntaryhmittäin
     ... and 17 more

In [6]:
db.Vero.Henk.lopulliset.tulot

statfin.PxWebAPI
  url: https://vero2.stat.fi/PXWeb/api/v1/fi/Vero/Henkiloasiakkaiden_tuloverot/lopulliset/tulot
  title: 01. Tulot
  index:
    (t) tulot_101.px 1.1 Tulot tulonsaajaryhmittäin ja tuloluokittain
    (t) tulot_103.px 1.2 Tulot tulonsaajaryhmittäin ja ikäluokittain
    (t) tulot_104.px 1.3 Tulot tulonsaajaryhmittäin ja sukupuolittain

In [7]:
db.Vero.Henk.lopulliset.tulot._101

statfin.Table
  url: https://vero2.stat.fi/PXWeb/api/v1/fi/Vero/Henkiloasiakkaiden_tuloverot/lopulliset/tulot/tulot_101.px
  title: 1.1 Tulot tulonsaajaryhmittäin ja tuloluokittain muuttujina Verovuosi, Erä, Tulonsaajaryhmä, Tuloluokka ja Tunnusluvut
  variables:
    [10]  Verovuosi       Verovuosi
    [226] Erä             Erä
    [13]  Tulonsaajaryhmä Tulonsaajaryhmä
    [28]  Tuloluokka      Tuloluokka
    [16]  Tunnusluvut     Tunnusluvut

In [8]:
tbl = db.Vero.Henk.lopulliset.tulot._101
tbl.Erä

statfin.Variable
  code: Erä
  text: Erä
  values:
    HVT_TULOT_10   1. Verotuspäätöksen saajien lukumäärä
    HVT_TULOT_20   1.1 Yleisesti verovelvolliset
    HVT_TULOT_30   1.2 Rajoitetusti verovelvolliset, joilla VML-vaatimus
    HVT_TULOT_40   1.3 Muut rajoitetusti verovelvolliset
    HVT_TULOT_50   2. Tulot yhteensä
    HVT_TULOT_60   3. Veronalaiset tulot yhteensä
    HVT_TULOT_70   4. Ansiotulot yhteensä
     ... and 219 more

In [11]:
q = tbl.query(Verovuosi=2023, Erä="HVT_TULOT_70", Tulonsaajaryhmä="Y", Tuloluokka="*", Tunnusluvut="*")
q()

,Verovuosi,Erä,Tulonsaajaryhmä,Tuloluokka,Sum,N,Mean,Q1,Q3,P10,P20,P30,P40,P50,P60,P70,P80,P90,Sum_muutos,N_muutos
0,2023,HVT_TULOT_70,Y,SS,159463594310,4797766,33237,15465,43557,7850,12904,17769,22885,28311,33881,39965,47968,61876,5.0,0.4
1,2023,HVT_TULOT_70,Y,1,658229778,349477,1883,633,2970,277,492,781,1118,1551,2093,2649,3300,4099,-1.6,-0.1
2,2023,HVT_TULOT_70,Y,2,2011384717,257209,7820,6489,9474,5496,6163,6831,7482,8107,8708,9248,9643,9667,-10.2,-10.4
3,2023,HVT_TULOT_70,Y,3,6085411616,499630,12180,11069,13436,10564,11069,11069,11423,11974,12546,13126,13750,14370,-8.3,-9.1
4,2023,HVT_TULOT_70,Y,4,8199355765,478264,17144,16011,18501,15261,15764,16245,16701,17213,17738,18254,18767,19359,-4.1,-4.6
5,2023,HVT_TULOT_70,Y,5,9650614204,439280,21969,20878,23532,20102,20618,21134,21652,22178,22711,23253,23813,24376,-2.5,-2.8
6,2023,HVT_TULOT_70,Y,6,11413956463,425930,26798,25788,28509,25017,25529,26051,26583,27121,27664,28224,28796,29374,-1.3,-1.5
7,2023,HVT_TULOT_70,Y,7,13448256579,424373,31690,30776,33495,29967,30509,31040,31574,32117,32660,33214,33778,34362,1.2,0.9
8,2023,HVT_TULOT_70,Y,8,14138050083,387433,36492,35695,38426,34590,35438,35956,36476,37018,37573,38137,38721,39332,3.1,2.8
9,2023,HVT_TULOT_70,Y,9,13420623135,325789,41194,40574,43301,38850,40324,40824,41341,41872,42419,43000,43614,44267,7.2,6.8
10,2023,HVT_TULOT_70,Y,10,11692180782,254952,45860,45465,48240,42816,45215,45715,46237,46781,47342,47935,48560,49236,7.6,7.2
11,2023,HVT_TULOT_70,Y,11,10076658513,199623,50478,50347,53177,46702,50094,50603,51129,51681,52255,52863,53508,54204,9.0,8.5
12,2023,HVT_TULOT_70,Y,12,8435132185,153462,54966,55184,58078,50204,54736,55443,55979,56540,57127,57753,58423,59141,10.5,10.0
13,2023,HVT_TULOT_70,Y,13,7026275928,118216,59436,60034,62996,53541,59027,60295,60847,61423,62029,62665,63355,64109,12.1,11.3
14,2023,HVT_TULOT_70,Y,14,5767720203,90474,63750,64439,67889,56272,62936,65107,65661,66253,66887,67539,68254,69045,12.0,11.4
15,2023,HVT_TULOT_70,Y,15,4764172661,70018,68042,68803,72817,58798,66987,69927,70530,71125,71773,72455,73190,74012,13.0,12.2
16,2023,HVT_TULOT_70,Y,16,3969575276,54899,72307,72854,77742,61138,70843,74333,75384,76002,76655,77353,78120,78958,13.5,12.4
17,2023,HVT_TULOT_70,Y,17,3300547019,43144,76501,77184,82654,63263,74728,78781,80246,80874,81552,82269,83047,83929,11.7,10.6
18,2023,HVT_TULOT_70,Y,18,2811726199,34915,80531,81024,87581,63959,78303,82948,85073,85746,86446,87194,87991,88879,13.6,12.6
19,2023,HVT_TULOT_70,Y,19,2387418790,28135,84856,85397,92455,66583,82339,87424,89884,90607,91291,92032,92893,93817,14.4,13.3
20,2023,HVT_TULOT_70,Y,20,2034182982,22925,88732,88966,97329,67905,85351,91504,94389,95444,96156,96918,97776,98745,14.6,13.5
21,2023,HVT_TULOT_70,Y,21,10008907312,95469,104839,98945,120710,69634,94242,100924,104174,107926,112282,117673,124265,133313,12.2,11.0
22,2023,HVT_TULOT_70,Y,22,3333834212,23368,142667,133438,170452,66222,118115,143000,151157,155716,160952,166985,174567,184062,9.3,7.7
23,2023,HVT_TULOT_70,Y,23,1541994909,8770,175826,147850,219357,58224,116650,172075,195693,202979,208945,215521,223762,234098,9.1,6.3
24,2023,HVT_TULOT_70,Y,24,838806341,4072,205994,151842,266351,56605,111002,187805,231198,248914,255361,262051,270544,281361,11.9,6.5
25,2023,HVT_TULOT_70,Y,25,1189577376,4882,243666,110006,343910,42604,80737,143823,234177,294968,313373,332099,358728,399180,2.0,-4.1
26,2023,HVT_TULOT_70,Y,26,653049803,2070,315483,74430,539750,30523,58773,90771,131204,218418,423645,514867,571416,678852,-1.3,-6.2
27,2023,HVT_TULOT_70,Y,27,605951479,987,613933,63871,830343,26641,50380,74626,96618,132989,201306,422662,1041529,1454200,-5.7,-22.3

In [15]:
tbl = statfin.StatFin().StatFin.ntp._11tj
tbl.query(Taloustoimi = "E2", Toimiala = "SSS")()

    Vuosineljännes Taloustoimi Toimiala  KAUSIT    TASM  TRENDI    TYOP
0           1990Q1          E2      SSS  1076.8  1098.9  1080.4  1077.0
1           1990Q2          E2      SSS  1068.3  1079.1  1072.5  1088.5
2           1990Q3          E2      SSS  1072.8  1014.3  1062.6  1019.8
3           1990Q4          E2      SSS  1043.6  1069.2  1046.0  1076.2
4           1991Q1          E2      SSS  1033.8  1029.5  1025.8  1033.4
..             ...         ...      ...     ...     ...     ...     ...
135         2023Q4          E2      SSS  1056.4  1053.8  1064.2  1060.1
136         2024Q1          E2      SSS  1076.3  1064.5  1066.4  1066.5
137         2024Q2          E2      SSS  1069.2  1108.5  1070.1  1101.8
138         2024Q3          E2      SSS  1068.6  1045.5  1072.7  1042.2
139         2024Q4          E2      SSS  1069.0  1064.6  1073.9  1072.6

[140 rows x 7 columns]