# AKShare 项目概览
- Document: https://akshare.akfamily.xyz
- GitHub: https://github.com/akfamily/akshare

## A股历史行情数据
https://akshare.akfamily.xyz/data/stock/stock.html
### 历史行情数据-东财
接口: stock_zh_a_hist

In [1]:
import akshare as ak

stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="600325", period="daily", start_date="20250428", end_date='20250430', adjust="")
print(stock_zh_a_hist_df)

           日期    股票代码    开盘    收盘    最高    最低     成交量          成交额    振幅  \
0  2025-04-28  600325  5.30  5.12  5.34  5.10  393706  203460659.0  4.55
1  2025-04-29  600325  5.10  5.11  5.15  5.06  198551  101549071.0  1.76
2  2025-04-30  600325  5.11  5.09  5.17  5.08  226502  115807219.0  1.76

    涨跌幅   涨跌额   换手率
0 -3.03 -0.16  1.53
1 -0.20 -0.01  0.77
2 -0.39 -0.02  0.88

In [5]:
spot_data = stock_zh_a_hist_df.iloc[-1].to_dict()
spot_data

{'日期': datetime.date(2025, 4, 30),
 '股票代码': '600325',
 '开盘': 5.11,
 '收盘': 5.09,
 '最高': 5.17,
 '最低': 5.08,
 '成交量': 226502,
 '成交额': 115807219.0,
 '振幅': 1.76,
 '涨跌幅': -0.39,
 '涨跌额': -0.02,
 '换手率': 0.88}

In [11]:
stock_individual_info_em_df = ak.stock_individual_info_em(symbol="600325")
spot_dict = dict(zip(stock_individual_info_em_df['item'], stock_individual_info_em_df['value']))
spot_dict.get('股票简称', "")

'华发股份'

### 历史行情数据-新浪
接口: stock_zh_a_daily

P.S. 建议切换为 stock_zh_a_hist 接口使用(该接口数据质量高, 访问无限制)

目标地址: https://finance.sina.com.cn/realstock/company/sh600006/nc.shtml(示例)

描述: 新浪财经-沪深京 A 股的数据, 历史数据按日频率更新; 注意其中的 sh689009 为 CDR, 请 通过 ak.stock_zh_a_cdr_daily 接口获取

限量: 单次返回指定沪深京 A 股上市公司指定日期间的历史行情日频率数据, 多次获取容易封禁 IP

In [22]:
stock_zh_a_daily_qfq_df = ak.stock_zh_a_daily(symbol="bj835185", start_date="20250421", end_date="20250425", adjust="qfq")
print(stock_zh_a_daily_qfq_df)

         date   open   high    low  close     volume       amount  \
0  2025-04-21  20.30  20.79  20.16  20.74  4273529.0   88153982.0
1  2025-04-22  21.02  21.40  20.56  20.63  4913558.0  102890216.0
2  2025-04-23  20.71  20.94  20.50  20.83  4923920.0  102113097.0
3  2025-04-24  20.89  20.89  20.02  20.02  4479001.0   91230839.0
4  2025-04-25  19.91  20.25  19.81  19.98  3040712.0   61077325.0

   outstanding_share  turnover
0       1.109173e+09  0.003853
1       1.109173e+09  0.004430
2       1.109173e+09  0.004439
3       1.109173e+09  0.004038
4       1.109173e+09  0.002741

### 历史行情数据-腾讯
```
接口: stock_zh_a_hist_tx
目标地址: https://gu.qq.com/sh000919/zs
描述: 腾讯证券-日频-股票历史数据; 历史数据按日频率更新, 当日收盘价请在收盘后获取
限量: 单次返回指定沪深京 A 股上市公司、指定周期和指定日期间的历史行情日频率数据
```

In [28]:
stock_zh_a_hist_tx_df = ak.stock_zh_a_hist_tx(symbol="sz300750", start_date="20250421", end_date="20250425", adjust="")
print(stock_zh_a_hist_tx_df)

  0%|          | 0/1 [00:00<?, ?it/s]

         date    open   close    high     low    amount
0  2025-04-21  225.46  231.36  235.00  224.18  220082.0
1  2025-04-22  230.00  230.69  231.16  227.20  169354.0
2  2025-04-23  235.00  233.35  238.75  233.00  191980.0
3  2025-04-24  234.50  236.87  238.66  232.25  181554.0
4  2025-04-25  237.20  236.60  237.92  235.09  127620.0

### [腾讯财经A+H历史行情数据](https://akshare.akfamily.xyz/data/stock/stock.html#id53 "Link to this heading")

接口: stock_zh_ah_daily

目标地址: https://gu.qq.com/hk02359/gp

描述: 腾讯财经-A+H 股数据

限量: 单次返回指定参数的 A+H 上市公司的历史行情数据

输入参数

| 名称  | 类型  | 描述  |
| --- | --- | --- |
| symbol | str | symbol="02318"; 港股股票代码, 可以通过 **ak.stock_zh_ah_name()** 函数获取 |
| start_year | str | start_year="2000"; 开始年份 |
| end_year | str | end_year="2019"; 结束年份 |
| adjust | str | adjust=""; 默认为空不复权; 'qfq': 前复权, 'hfq': 后复权 |

输出参数

| 名称  | 类型  | 描述  |
| --- | --- | --- |
| 日期  | object | -   |
| 开盘  | float64 | -   |
| 收盘  | float64 | -   |
| 最高  | float64 | -   |
| 最低  | float64 | -   |
| 成交量 | float64 | -   |

In [2]:
stock_zh_ah_daily_df = ak.stock_zh_ah_daily(symbol="06823", start_year="2022", end_year="2025", adjust="")
stock_zh_ah_daily_df

  0%|          | 0/3 [00:00<?, ?it/s]

              日期     开盘     收盘     最高     最低         成交量
0     2022-01-03  10.50  10.54  10.58  10.50   2134210.0
1     2022-01-04  10.56  10.64  10.64  10.54   2068180.0
2     2022-01-05  10.64  10.62  10.66  10.56   3380549.0
3     2022-01-06  10.62  10.62  10.64  10.56   2351263.0
4     2022-01-07  10.62  10.66  10.66  10.58   2769891.0
...          ...    ...    ...    ...    ...         ...
1305  2025-04-25  10.90  10.94  10.96  10.80   6221558.0
1306  2025-04-28  10.94  11.00  11.08  10.80   6461504.0
1307  2025-04-29  11.00  11.10  11.10  11.00  11761209.0
1308  2025-04-30  11.10  11.04  11.10  10.90  14136934.0
1309  2025-05-02  11.00  11.02  11.08  10.94   6488551.0

[1310 rows x 6 columns]

## A股实时行情数据
### 实时行情数据-东财 (沪深京 A 股)
接口: stock_zh_a_spot_em

目标地址: https://quote.eastmoney.com/center/gridlist.html#hs_a_board

In [13]:
stock_zh_a_spot_em_df = ak.stock_zh_a_spot_em()
stock_zh_a_spot_em_df

  0%|          | 0/57 [00:00<?, ?it/s]

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,838810,春光智能,21.16,29.98,4.88,137108.0,2.631021e+08,31.70,21.16,...,4.01,30.76,121.62,6.28,1.449460e+09,9.432455e+08,0.0,0.0,157.42,144.91
1,2,870199,倍益康,29.19,29.96,6.73,86980.0,2.358308e+08,27.25,29.19,...,5.88,23.38,-305.16,3.82,1.988125e+09,1.085912e+09,0.0,0.0,44.50,48.85
2,3,301387,光大同创,40.36,20.01,6.73,111781.0,4.297520e+08,18.32,40.36,...,5.05,26.36,60.49,2.62,4.297977e+09,1.711296e+09,0.0,0.0,33.47,17.67
3,4,688667,菱电电控,54.90,20.00,9.15,23643.0,1.255980e+08,16.07,54.90,...,7.54,4.56,40.69,1.73,2.844486e+09,2.844486e+09,0.0,0.0,35.25,36.60
4,5,301008,宏昌科技,27.54,20.00,4.59,123597.0,3.203784e+08,18.61,27.54,...,3.49,12.68,64.99,2.81,3.100641e+09,2.684236e+09,0.0,0.0,43.36,46.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5709,5710,000018,神城A退,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00
5710,5711,000015,PT中浩A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00
5711,5712,000013,*ST石化A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00
5712,5713,000005,ST星源,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00
5713,5714,000003,PT金田A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00

### 实时行情数据-雪球
接口: stock_individual_spot_xq

目标地址: https://xueqiu.com/S/SH513520

描述: 雪球-行情中心-个股

限量: 单次获取指定 symbol 的最新行情数据

## 美股
### 实时行情数据-东财
```
接口: stock_us_spot_em
目标地址: https://quote.eastmoney.com/center/gridlist.html#us_stocks
描述: 东方财富网-美股-实时行情
限量: 单次返回美股所有上市公司的实时行情数据
```

In [ ]:
# 不稳定
stock_us_spot_em_df = ak.stock_us_spot_em()
print(stock_us_spot_em_df)

### 实时行情数据-新浪
```
接口: stock_us_spot
目标地址: https://finance.sina.com.cn/stock/usstock/sector.shtml
描述: 新浪财经-美股; 获取的数据有 15 分钟延迟; 建议使用 ak.stock_us_spot_em() 来获取数据
限量: 单次返回美股所有上市公司的实时行情数据
```

In [ ]:
# Very slow
us_stock_current_df = ak.stock_us_spot()
print(us_stock_current_df)

### 历史行情数据-东财
```
接口: stock_us_hist
目标地址: https://quote.eastmoney.com/us/ENTX.html#fullScreenChart
描述: 东方财富网-行情-美股-每日行情
限量: 单次返回指定上市公司的指定 adjust 后的所有历史行情数据；注意其中复权参数是否生效！
```

In [31]:
stock_us_hist_df = ak.stock_us_hist(symbol='106.TTE', period="daily", start_date="20200101", end_date="20240214", adjust="qfq")
print(stock_us_hist_df)

              日期      开盘      收盘      最高      最低      成交量          成交额    振幅  \
0     2020-01-02  37.780  37.910  37.920  37.470  1166549   64267605.0  1.21
1     2020-01-03  37.910  38.110  38.360  37.860  1518977   84342940.0  1.32
2     2020-01-06  39.370  39.150  39.550  38.810  3516935  198886813.0  1.94
3     2020-01-07  38.950  38.830  38.970  38.340  2464108  138120786.0  1.61
4     2020-01-08  38.580  38.490  38.740  38.250  2831404  158168344.0  1.26
...          ...     ...     ...     ...     ...      ...          ...   ...
1032  2024-02-08  59.228  60.028  60.168  59.118  3348869  214143178.0  1.78
1033  2024-02-09  60.248  60.148  60.368  59.928  3474556  223631050.0  0.73
1034  2024-02-12  60.238  60.468  60.658  60.028  3213256  207519393.0  1.05
1035  2024-02-13  61.048  60.268  61.118  59.948  3306680  212993175.0  1.93
1036  2024-02-14  60.568  60.468  60.873  60.218  4014478  259516349.0  1.09

       涨跌幅    涨跌额   换手率
0     1.89  0.702  0.04
1     0.53  0.200  0.06
2     2.73  1.040  0.14
3    -0.82 -0.320  0.09
4    -0.88 -0.340  0.11
...    ...    ...   ...
1032  1.94  1.140  0.14
1033  0.20  0.120  0.15
1034  0.53  0.320  0.14
1035 -0.33 -0.200  0.14
1036  0.33  0.200  0.17

[1037 rows x 11 columns]

### 历史行情数据-新浪
```
接口: stock_us_daily
目标地址: http://finance.sina.com.cn/stock/usstock/sector.shtml
描述: 美股历史行情数据，设定 adjust="qfq" 则返回前复权后的数据，默认 adjust="", 则返回未复权的数据，历史数据按日频率更新
限量: 单次返回指定上市公司的指定 adjust 后的所有历史行情数据
```

In [33]:
stock_us_daily_df = ak.stock_us_daily(symbol="AAPL", adjust="")
print(stock_us_daily_df)

           date     open    high       low   close       volume
0    1984-09-07   26.500   26.87   26.2500   26.50    2981600.0
1    1984-09-10   26.500   26.62   25.8700   26.37    2346400.0
2    1984-09-11   26.620   27.37   26.6200   26.87    5444000.0
3    1984-09-12   26.870   27.00   26.1200   26.12    4773600.0
4    1984-09-13   27.500   27.62   27.5000   27.50    7429600.0
...         ...      ...     ...       ...     ...          ...
9684 2025-04-28  210.000  211.50  207.4600  210.14   38742989.0
9685 2025-04-29  208.693  212.24  208.3700  211.21   36827481.0
9686 2025-04-30  209.300  213.58  206.6705  212.50   52286229.0
9687 2025-05-01  209.080  214.56  208.9000  213.32   57365674.0
9688 2025-05-02  206.090  206.99  202.1600  205.35  101010494.0

[9689 rows x 6 columns]

## 港股
### 实时行情数据-东财
```
接口: stock_hk_spot_em
目标地址: http://quote.eastmoney.com/center/gridlist.html#hk_stocks
描述: 所有港股的实时行情数据; 该数据有 15 分钟延时
限量: 单次返回最近交易日的所有港股的数据

stock_hk_spot_em_df = ak.stock_hk_spot_em()
print(stock_hk_spot_em_df)
```

### 实时行情数据-新浪
```
港股-实时行情数据是从新浪财经获取的数据, 更新频率为实时, 由于新浪服务器因素行情延时 15 分钟
接口: stock_hk_spot
目标地址: http://vip.stock.finance.sina.com.cn/mkt/#qbgg_hk
描述: 获取所有港股的实时行情数据 15 分钟延时
限量: 单次返回当前时间戳的所有港股的数据

stock_hk_spot_df = ak.stock_hk_spot()
print(stock_hk_spot_df)
```

### 历史行情数据-东财
```
接口: stock_hk_hist
目标地址: https://quote.eastmoney.com/hk/08367.html
描述: 港股-历史行情数据, 可以选择返回复权后数据, 更新频率为日频
限量: 单次返回指定上市公司的历史行情数据
```

In [37]:
stock_hk_hist_df = ak.stock_hk_hist(symbol="00001", period="daily", start_date="20250421", end_date="20250425", adjust="")
print(stock_hk_hist_df)

           日期     开盘     收盘     最高    最低       成交量          成交额    振幅   涨跌幅  \
0  2025-04-22  42.25  43.30  43.50  42.2  10434592  449349088.0  3.08  2.73
1  2025-04-23  43.95  43.50  44.30  43.4   9974373  436371264.0  2.08  0.46
2  2025-04-24  43.10  42.95  43.65  42.8   7491657  322799872.0  1.95 -1.26
3  2025-04-25  43.35  43.25  44.10  43.2   6170961  268556464.0  2.10  0.70

    涨跌额   换手率
0  1.15  0.27
1  0.20  0.26
2 -0.55  0.20
3  0.30  0.16

### 历史行情数据-新浪
```
接口: stock_hk_daily
目标地址: http://stock.finance.sina.com.cn/hkstock/quotes/01336.html(个例)
描述:港股-历史行情数据, 可以选择返回复权后数据,更新频率为日频
限量: 单次返回指定上市公司的历史行情数据(包括前后复权因子), 提供新浪财经拥有的该股票的所有数据( 并不等于该股票从上市至今的数据)
```

In [38]:
stock_hk_daily_hfq_df = ak.stock_hk_daily(symbol="00700", adjust="hfq")
print(stock_hk_daily_hfq_df)

            date      open      high       low     close       volume
0     2004-06-16     4.375     4.625     4.075     4.150  439775000.0
1     2004-06-17     4.150     4.375     4.125     4.225   83801500.0
2     2004-06-18     4.200     4.250     3.950     4.025   36598000.0
3     2004-06-21     4.125     4.125     3.950     4.000   22817000.0
4     2004-06-23     4.050     4.450     4.025     4.425   55016000.0
...          ...       ...       ...       ...       ...          ...
5126  2025-04-25  2629.930  2658.930  2604.930  2620.930   28746958.0
5127  2025-04-28  2641.930  2641.930  2603.930  2620.930   13805160.0
5128  2025-04-29  2618.930  2621.930  2574.930  2594.930   16367401.0
5129  2025-04-30  2604.930  2615.930  2576.930  2615.930   15312733.0
5130  2025-05-02  2620.930  2678.930  2616.930  2668.930   13240838.0

[5131 rows x 6 columns]

## 股票代码

In [ ]:
stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SH600000")
print(stock_individual_spot_xq_df.dtypes)

In [3]:
sh_list = ak.stock_info_sh_name_code()
sh_list

        证券代码  证券简称                公司全称        上市日期
0     600000  浦发银行      上海浦东发展银行股份有限公司  1999-11-10
1     600004  白云机场      广州白云国际机场股份有限公司  2003-04-28
2     600006  东风股份          东风汽车股份有限公司  1999-07-27
3     600007  中国国贸      中国国际贸易中心股份有限公司  1999-03-12
4     600008  首创环保    北京首创生态环保集团股份有限公司  2000-04-27
...      ...   ...                 ...         ...
1689  605580  恒盛能源          恒盛能源股份有限公司  2021-08-19
1690  605588  冠石科技        南京冠石科技股份有限公司  2021-08-12
1691  605589  圣泉集团        济南圣泉集团股份有限公司  2021-08-10
1692  605598  上海港湾  上海港湾基础建设(集团)股份有限公司  2021-09-17
1693  605599  菜百股份       北京菜市口百货股份有限公司  2021-09-09

[1694 rows x 4 columns]

In [4]:
sz_list = ak.stock_info_sz_name_code()
sz_list

       板块    A股代码   A股简称      A股上市日期           A股总股本          A股流通股本    所属行业
0      主板  000001   平安银行  1991-04-03  19,405,918,198  19,405,600,653   J 金融业
1      主板  000002  万  科Ａ  1991-01-29   9,724,196,533   9,716,812,790   K 房地产
2      主板  000004  *ST国华  1990-12-01     132,380,282     126,288,093  I 信息技术
3      主板  000006   深振业Ａ  1992-04-27   1,349,995,046   1,349,987,396   K 房地产
4      主板  000007    全新好  1992-04-13     346,448,044     346,448,044   K 房地产
...   ...     ...    ...         ...             ...             ...     ...
2861  创业板  301633   港迪技术  2024-11-07      55,680,000      13,920,000  I 信息技术
2862  创业板  301658   首航新能  2025-04-02     412,371,135      38,728,009   C 制造业
2863  创业板  301662   宏工科技  2025-04-17      80,000,000      15,776,325   C 制造业
2864  创业板  301665   泰禾股份  2025-04-11     450,000,000      35,906,289   C 制造业
2865  创业板  302132   中航成飞  2010-08-27   2,676,782,376     590,719,499   C 制造业

[2866 rows x 7 columns]

In [5]:
hk_list = ak.stock_hk_main_board_spot_em()
hk_list

  0%|          | 0/23 [00:00<?, ?it/s]

,序号,代码,名称,最新价,涨跌额,涨跌幅,今开,最高,最低,昨收,成交量,成交额
0,1,01079,松景科技,0.057,0.025,78.13,0.034,0.068,0.034,0.032,50688000.0,2836386.0
1,2,00613,梧桐国际,0.450,0.120,36.36,0.340,0.500,0.335,0.330,1888000.0,771240.0
2,3,01396,粤港湾控股,1.680,0.440,35.48,1.240,1.690,1.190,1.240,3702601.0,5625249.0
3,4,01049,时富投资,1.050,0.200,23.53,0.880,1.050,0.880,0.850,16525.0,16340.0
4,5,01421,恒昌集团国际,0.300,0.055,22.45,0.250,0.300,0.250,0.245,75500.0,19590.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2347,2348,00102,凯升控股,NaN,NaN,NaN,NaN,NaN,NaN,0.047,NaN,NaN
2348,2349,00065,弘海高新资源,NaN,NaN,NaN,NaN,NaN,NaN,0.475,NaN,NaN
2349,2350,00059,天誉置业,NaN,NaN,NaN,NaN,NaN,NaN,0.010,NaN,NaN
2350,2351,00009,金奥国际,NaN,NaN,NaN,NaN,NaN,NaN,0.013,NaN,NaN
2351,2352,00007,智富资源投资,NaN,NaN,NaN,NaN,NaN,NaN,0.032,NaN,NaN

In [9]:
from sqlalchemy import create_engine, Column, Integer, String, text, select
from sqlalchemy.orm import DeclarativeBase

class Base(DeclarativeBase):
    pass

class StockListing(Base):
    __tablename__ = 'stock_listings'
    
    id = Column(Integer, primary_key=True)
    market = Column(String)  # 'SH', 'SZ', or 'HK'
    code = Column(String)
    name = Column(String)
    listing_date = Column(String, nullable=True)
    
def write_stock_lists_to_db(sh_list, sz_list, hk_list, db_path='finance.db'):
    """
    Write Shanghai, Shenzhen, and Hong Kong stock listings to SQLite database
    
    Parameters:
    -----------
    sh_list : DataFrame
        Shanghai stock listings
    sz_list : DataFrame
        Shenzhen stock listings 
    hk_list : DataFrame
        Hong Kong stock listings
    db_path : str
        Path to SQLite database file
    """
    engine = create_engine(f'sqlite:///{db_path}')
    Base.metadata.create_all(engine)
    
    # Process Shanghai listings
    sh_records = []
    for _, row in sh_list.iterrows():
        sh_records.append({
            'market': 'SH',
            'code': row['证券代码'],
            'name': row['证券简称'],
            'listing_date': row['上市日期']
        })
    
    # Process Shenzhen listings    
    sz_records = []
    for _, row in sz_list.iterrows():
        sz_records.append({
            'market': 'SZ', 
            'code': row['A股代码'],
            'name': row['A股简称'],
            'listing_date': row['A股上市日期']
        })
        
    # Process Hong Kong listings
    hk_records = []
    for _, row in hk_list.iterrows():
        hk_records.append({
            'market': 'HK',
            'code': str(row['代码']),
            'name': row['名称'],
            'listing_date': None
        })
    
    # Write all records to database
    with engine.connect() as conn:
        # Clear existing data
        conn.execute(text("DELETE FROM stock_listings"))
        conn.execute(text("INSERT INTO stock_listings (market, code, name, listing_date) VALUES (:market, :code, :name, :listing_date)"), 
                    sh_records + sz_records + hk_records)
        conn.commit()

In [10]:
# Execute the function
write_stock_lists_to_db(sh_list, sz_list, hk_list)

# Verify the data
engine = create_engine('sqlite:///finance.db')
with engine.connect() as conn:
    result = conn.execute(text("SELECT market, COUNT(*) as count FROM stock_listings GROUP BY market"))
    for row in result:
        print(f"{row.market}: {row.count} listings")

HK: 2352 listings
SH: 1694 listings
SZ: 2866 listings

## 美股代码
ak.stock_us_spot_em()

In [32]:
ak.stock_us_spot_em=ak.stock_us_spot_em()
ak.stock_us_spot_em

  0%|          | 0/118 [00:00<?, ?it/s]

,序号,名称,最新价,涨跌额,涨跌幅,开盘价,最高价,最低价,昨收价,总市值,市盈率,成交量,成交额,振幅,换手率,代码
0,1,Polyrizon Ltd,1.010,0.757,298.58,0.523,1.190,0.511,0.253,40209223.0,-26.03,360806992.0,320261296.0,267.88,906.30,105.PLRZ
1,2,Freight Technologies Inc,2.080,1.095,111.21,3.130,3.490,1.930,0.985,4711354.0,-0.84,163965267.0,413794320.0,158.40,7238.85,105.FRGT
2,3,Celularity Inc Wt,0.060,0.029,93.55,0.036,0.090,0.036,0.031,NaN,NaN,48354.0,3393.0,175.81,NaN,105.CELUW
3,4,Impact BioMedical Inc,0.748,0.348,87.00,0.550,0.939,0.460,0.400,9039888.0,-0.37,191836868.0,145578849.0,119.75,1587.34,107.IBO
4,5,Click Holdings Ltd,0.345,0.129,59.50,0.221,0.394,0.210,0.216,10929600.0,12.36,35336562.0,10934333.0,84.93,111.54,105.CLIK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11845,11846,Apple Inc Notes 2027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,105.AAPL27
11846,11847,Apple Inc Notes 2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,105.AAPL26
11847,11848,Apple Inc Notes 2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,105.AAPL25
11848,11849,Apple Inc Notes 2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,105.AAPL24
11849,11850,Apple Inc Notes 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,105.AAPL22